//
//  QuizBrain.swift
//  EnglishStudyApp
//
//  Created by mayo on 2020/11/26.
//

import Foundation

struct WordQuiz{
    
    let QuizList=[
//     食事
    [
//        果物１
        [
    Quiz(answer:"apple",section1:"apple", section2:"pineapple", section3:"pear",sound:"apple"),
    Quiz(answer:"melon",section1:"watermelon", section2:"lemon", section3:"melon",sound:"melon"),
    Quiz(answer:"banana",section1:"banana", section2:"_orange", section3:"cherries",sound:"banana"),
    Quiz(answer:"_orange",section1:"_orange", section2:"grapes", section3:"banana",sound:"_orange"),
    Quiz(answer:"cherries",section1:"strawberry", section2:"cheese", section3:"cherries",sound:"cherries"),
    Quiz(answer:"peach",section1:"pineapple", section2:"peach", section3:"pear",sound:"peach"),
    Quiz(answer:"chestnut",section1:"cheese", section2:"chestnut", section3:"apple",sound:"chestnut"),
    ],
//        果物２
        [
    Quiz(answer:"pear",section1:"pear", section2:"pineapple", section3:"bread",sound:"pear"),
    Quiz(answer:"persimmon",section1:"pineapple", section2:"green pepper", section3:"persimmon",sound:"persimmon"),
    Quiz(answer:"pineapple",section1:"pineapple", section2:"apple", section3:"pear",sound:"pineapple"),
    Quiz(answer:"grapefruit",section1:"grapes", section2:"grapefruit", section3:"green tea",sound:"grapefruit"),
    Quiz(answer:"grapes",section1:"grapefruit", section2:"green pepper", section3:"grapes",sound:"grapes"),
    Quiz(answer:"strawberry",section1:"strawberry", section2:"lemon", section3:"potato",sound:"strawberry"),
    Quiz(answer:"watermelon",section1:"melon", section2:"watermelon", section3:"lemon",sound:"watermelon"),
    Quiz(answer:"kiwi",section1:"kiwi", section2:"lemon", section3:"kimchi",sound:"kiwi"),
    Quiz(answer:"lemon",section1:"bowl", section2:"lemon", section3:"eggplant",sound:"lemon"),
    ],
//        野菜１
        [
        Quiz(answer:"cabbage",section1:"cabbage", section2:"sugar", section3:"cheese",sound:"cabbage"),
        Quiz(answer:"carrot",section1:"candy", section2:"carrot", section3:"soup",sound:"carrot"),
        Quiz(answer:"corn",section1:"parfait", section2:"peach", section3:"corn",sound:"corn"),
        Quiz(answer:"potato",section1:"potato", section2:"tomato", section3:"potatochips",sound:"potato"),
        Quiz(answer:"pumpkin",section1:"pineapple", section2:"pumpkin", section3:"soba noodle",sound:"pumpkin"),
        Quiz(answer:"cucumber",section1:"cup", section2:"corn", section3:"cucumber",sound:"cucumber"),
        Quiz(answer:"tomato",section1:"tomato", section2:"melon", section3:"fork",sound:"tomato"),
    ]
//    野菜２
    ,[
        Quiz(answer:"eggplant",section1:"egg", section2:"eggplant", section3:"rice cake",sound:"eggplant"),
        Quiz(answer:"turnip",section1:"spoon", section2:"croissant", section3:"turnip",sound:"turnip"),
        Quiz(answer:"green pepper",section1:"green pepper", section2:"_orange", section3:"water",sound:"green pepper"),
        Quiz(answer:"Japanese radish",section1:"plate", section2:"Japanese radish", section3:"strawberry",sound:"Japanese radish"),
        Quiz(answer:"lettuce",section1:"Japanese radish", section2:"miso soup", section3:"lettuce",sound:"lettuce"),
        Quiz(answer:"mushroom",section1:"mushroom", section2:"music room", section3:"cookie",sound:"mushroom"),
        Quiz(answer:"onion",section1:"omelet", section2:"onion", section3:"fried chicken",sound:"onion"),
    ],
//        食べ物1
        [
        Quiz(answer:"bread",section1:"brush", section2:"bread", section3:"ham",sound:"bread"),
        Quiz(answer:"cereal",section1:"comic", section2:"rice", section3:"cereal",sound:"cereal"),
        Quiz(answer:"cheese",section1:"cheese", section2:"calender", section3:"backpack",sound:"cheese"),
        Quiz(answer:"pepper",section1:"pear", section2:"pepper", section3:"green pepper",sound:"pepper"),
        Quiz(answer:"rice cake",section1:"cake", section2:"stew", section3:"rice cake",sound:"rice cake"),
        Quiz(answer:"rice",section1:"rice", section2:"japanese omelet", section3:"pickles",sound:"rice"),
        Quiz(answer:"croissant",section1:"corn", section2:"croissant", section3:"gratin",sound:"croissant"),
        Quiz(answer:"salt",section1:"egg", section2:"PC", section3:"salt",sound:"salt"),
    ],
//        食べ物２
        [
        Quiz(answer:"sausage",section1:"salt", section2:"sandwiches", section3:"sausage",sound:"sausage"),
        Quiz(answer:"egg",section1:"egg", section2:"bag", section3:"onion",sound:"egg"),
        Quiz(answer:"soy sauce",section1:"kimchi", section2:"soy sauce",  section3:"french fries",sound:"soy sauce"),
        Quiz(answer:"_fish",section1:"pumpkin", section2:"straw hat",  section3:"_fish",sound:"_fish"),
        Quiz(answer:"sugar",section1:"salt", section2:"sugar", section3:"sausage",sound:"sugar"),
        Quiz(answer:"ham",section1:"humbergur", section2:"hat", section3:"ham",sound:"ham"),
        Quiz(answer:"meat",section1:"meat", section2:"melon", section3:"lemon",sound:"meat"),
        Quiz(answer:"yogurt",section1:"medicine", section2:"yogurt", section3:"cream puff",sound:"yogurt"),
    ],
//        料理１
        [
        Quiz(answer:"bibimbap",section1:"bag", section2:"pajamas", section3:"bibimbap",sound:"bibimbap"),
        Quiz(answer:"kimchi",section1:"kimchi", section2:"egg", section3:"salad",sound:"kimchi"),
        Quiz(answer:"sandwiches",section1:"glove", section2:"sandwiches", section3:"mirror",sound:"sandwiches"),
        Quiz(answer:"curry and rice",section1:"fried prawn", section2:"soba noodle", section3:"curry and rice",sound:"curry and rice"),
        Quiz(answer:"Korean soup",section1:"Korean soup", section2:"corn", section3:"medicine",sound:"Korean soup"),
        Quiz(answer:"french fries",section1:"turnip", section2:"french fries", section3:"_fish",sound:"french fries"),
        Quiz(answer:"miso soup",section1:"melon", section2:"lemon", section3:"miso soup",sound:"miso soup"),
        Quiz(answer:"soba noodle",section1:"soba noodle", section2:"corn", section3:"comic",sound:"soba noodle"),
    ],
        //        料理２
        [
        Quiz(answer:"fried chicken",section1:"classroom", section2:"fried chicken", section3:"soccer ball",sound:"fried chicken"),
        Quiz(answer:"namul",section1:"kimchi", section2:"music room", section3:"namul",sound:"namul"),
        Quiz(answer:"soup",section1:"soup", section2:"chocolate", section3:"cookie",sound:"soup"),
        Quiz(answer:"fried prawn",section1:"mushroom", section2:"fried prawn", section3:"jellyfish",sound:"fried prawn"),
        Quiz(answer:"noodles",section1:"ice cream", section2:"rice ball", section3:"noodles",sound:"noodles"),
        Quiz(answer:"spaghetti",section1:"spaghetti", section2:"tomato", section3:"potato",sound:"spaghetti"),
        Quiz(answer:"gratin",section1:"cucumber", section2:"gratin", section3:"spaghetti",sound:"gratin"),
        Quiz(answer:"omelet",section1:"cabbage", section2:"artist", section3:"omelet",sound:"omelet"),
    ],
        //        料理３
        [
        Quiz(answer:"steak",section1:"steak", section2:"rice", section3:"stew",sound:"steak"),
        Quiz(answer:"pickles",section1:"pineapple", section2:"pickles", section3:"meat",sound:"pickles"),
        Quiz(answer:"stew",section1:"steak", section2:"candy", section3:"stew",sound:"stew"),
        Quiz(answer:"humbergur",section1:"humbergur", section2:"ham", section3:"popcorn",sound:"humbergur"),
        Quiz(answer:"pizza",section1:"pear", section2:"pizza", section3:"pineapple",sound:"pizza"),
        Quiz(answer:"hotdog",section1:"cereal", section2:"cake", section3:"hotdog",sound:"hotdog"),
        Quiz(answer:"rice ball",section1:"watermelon", section2:"rice ball", section3:"kiwi",sound:"rice ball"),
        Quiz(answer:"salad",section1:"spaghetti", section2:"omelet", section3:"salad",sound:"salad"),
        Quiz(answer:"japanese omelet",section1:"japanese omelet", section2:"pudding", section3:"doughnut",sound:"japanese omelet"),
    ],
//        飲み物1
        [
        Quiz(answer:"beer",section1:"bread", section2:"bag", section3:"beer",sound:"beer"),
        Quiz(answer:"coffee",section1:"coffee", section2:"egg", section3:"persimmon",sound:"coffee"),
        Quiz(answer:"green tea",section1:"green pepper", section2:"green tea", section3:"juice",sound:"green tea"),
        Quiz(answer:"juice",section1:"bowl", section2:"stew", section3:"juice",sound:"juice"),
        Quiz(answer:"milk",section1:"milk", section2:"melon", section3:"omelet",sound:"milk"),
        Quiz(answer:"tea",section1:"croissant", section2:"tea", section3:"pancake",sound:"tea"),
        Quiz(answer:"water",section1:"_orange", section2:"banana", section3:"water",sound:"water"),
        Quiz(answer:"wine",section1:"wine", section2:"water", section3:"kiwi",sound:"wine"),
     ],
//        おやつ
        [
        Quiz(answer:"cake",section1:"yogurt", section2:"_fish", section3:"cake",sound:"cake"),
        Quiz(answer:"potatochips",section1:"potatochips", section2:"tomato", section3:"hotdog",sound:"potatochips"),
        Quiz(answer:"candy",section1:"cherries", section2:"candy", section3:"cap",sound:"candy"),
        Quiz(answer:"pudding",section1:"pineapple", section2:"pickles", section3:"pudding",sound:"pudding"),
        Quiz(answer:"chocolate",section1:"chocolate", section2:"doughnut",  section3:"soup",sound:"chocolate"),
        Quiz(answer:"cookie",section1:"rice", section2:"cookie", section3:"carrot",sound:"cookie"),
        Quiz(answer:"cream puff",section1:"sweater", section2:"necktie", section3:"cream puff",sound:"cream puff"),
        Quiz(answer:"doughnut",section1:"doughnut", section2:"hotdog", section3:"watch",sound:"doughnut"),
        Quiz(answer:"ice cream",section1:"pudding", section2:"ice cream", section3:"parfait",sound:"ice cream"),
        Quiz(answer:"pancake",section1:"glass", section2:"parfait", section3:"pancake",sound:"pancake"),
        Quiz(answer:"parfait",section1:"parfait", section2:"pancake", section3:"milk",sound:"parfait"),
        Quiz(answer:"popcorn",section1:"potato", section2:"popcorn", section3:"melon",sound:"popcorn"),
     ],
//        食器
        [
        Quiz(answer:"bowl",section1:"bag", section2:"bowl", section3:"bride",sound:"bowl"),
        Quiz(answer:"chopsticks",section1:"spoon", section2:"beer", section3:"chopsticks",sound:"chopsticks"),
        Quiz(answer:"cup",section1:"cup", section2:"cap", section3:"pizza",sound:"cup"),
        Quiz(answer:"fork",section1:"_fish", section2:"fork", section3:"sugar",sound:"fork"),
        Quiz(answer:"glass",section1:"dancer", section2:"water", section3:"glass",sound:"glass"),
        Quiz(answer:"plate",section1:"plate", section2:"pants", section3:"pineapple",sound:"plate"),
        Quiz(answer:"spoon",section1:"sugar", section2:"spoon", section3:"mushroom",sound:"spoon"),
    ]],
//        生き物
        [
            
            [
        Quiz(answer:"crow",section1:"cow", section2:"crow",section3:"fox",sound:"crow"),
        Quiz(answer:"giraffe",section1:"flying_fish", section2:"rabbit",section3:"giraffe",sound:"giraffe"),
        Quiz(answer:"monkey",section1:"monkey", section2:"elephant",section3:"crane",sound:"monkey"),
        Quiz(answer:"tiger",section1:"necktie", section2:"tiger",section3:"jellyfish",sound:"tiger"),
        Quiz(answer:"bear",section1:"hippo", section2:"deer",section3:"bear",sound:"bear"),
        Quiz(answer:"deer",section1:"deer", section2:"lion",section3:"dog",sound:"deer"),
        Quiz(answer:"goat",section1:"zebra", section2:"goat",section3:"sheep",sound:"goat"),
        Quiz(answer:"mouse",section1:"gorilla", section2:"whale",section3:"mouse",sound:"mouse"),
    ],[
        Quiz(answer:"turtle",section1:"turtle", section2:"butterfly",section3:"pig",sound:"turtle"),
        Quiz(answer:"bird",section1:"pig", section2:"bird",section3:"camel",sound:"bird"),
        Quiz(answer:"dog",section1:"duck", section2:"wolf",section3:"dog",sound:"dog"),
        Quiz(answer:"gorilla",section1:"gorilla", section2:"crow",section3:"kangaroo",sound:"gorilla"),
        Quiz(answer:"octopus",section1:"octopus", section2:"koala",section3:"whale",sound:"octopus"),
        Quiz(answer:"whale",section1:"dolphin", section2:"whale",section3:"lion",sound:"whale"),
        Quiz(answer:"camel",section1:"wolf", section2:"cat",section3:"camel",sound:"camel"),
        Quiz(answer:"dolphin",section1:"chicken", section2:"duck",section3:"dolphin",sound:"dolphin"),
        Quiz(answer:"hippo",section1:"hippo", section2:"dolphin",section3:"elephant",sound:"hippo"),
    ],[
        Quiz(answer:"panda",section1:"sheep", section2:"panda", section3:"pig",sound:"panda"),
        Quiz(answer:"wolf",section1:"horse", section2:"mouse", section3:"wolf",sound:"wolf"),
        Quiz(answer:"duck",section1:"duck", section2:"dolphin", section3:"koala",sound:"duck"),
        Quiz(answer:"cat",section1:"crow", section2:"cat",  section3:"snake",sound:"cat"),
        Quiz(answer:"horse",section1:"lobster", section2:"starfish", section3:"horse",sound:"horse"),
        Quiz(answer:"penguin",section1:"penguin", section2:"pig", section3:"_fish",sound:"penguin"),
        Quiz(answer:"zebra",section1:"hippo", section2:"zebra", section3:"chicken",sound:"zebra"),
        Quiz(answer:"chick",section1:"chicken", section2:"crocodile", section3:"chick",sound:"chick"),
        Quiz(answer:"elephant",section1:"elephant", section2:"starfish", section3:"mouse",sound:"elephant"),
    ],[
        Quiz(answer:"jellyfish",section1:"_fish", section2:"jellyfish", section3:"flying_fish",sound:"jellyfish"),
        Quiz(answer:"pig",section1:"crane", section2:"cat", section3:"pig",sound:"pig"),
        Quiz(answer:"chicken",section1:"chicken", section2:"bear", section3:"horse",sound:"chicken"),
        Quiz(answer:"_fish",section1:"jellyfish", section2:"_fish", section3:"flying_fish",sound:"_fish"),
        Quiz(answer:"kangaroo",section1:"rabbit", section2:"zebra", section3:"kangaroo",sound:"kangaroo"),
        Quiz(answer:"rabbit",section1:"rabbit", section2:"kangaroo", section3:"panda",sound:"rabbit"),
        Quiz(answer:"cow",section1:"camel", section2:"cow", section3:"crow",sound:"cow"),
        Quiz(answer:"flying_fish",section1:"bear", section2:"goat", section3:"flying_fish",sound:"flying_fish"),
        Quiz(answer:"koala",section1:"koala", section2:"rabbit", section3:"kangaroo",sound:"koala"),
    ],[
        Quiz(answer:"sheep",section1:"turtle", section2:"sheep",section3:"mouse",sound:"sheep"),
        Quiz(answer:"crane",section1:"cat", section2:"flying_fish",section3:"crane",sound:"crane"),
        Quiz(answer:"fox",section1:"fox", section2:"bird",section3:"six",sound:"fox"),
        Quiz(answer:"lion",section1:"cow", section2:"lion",section3:"ladybug",sound:"lion"),
        Quiz(answer:"snake",section1:"crane", section2:"duck",section3:"snake",sound:"snake"),
        Quiz(answer:"crocodile",section1:"crocodile", section2:"camel",section3:"cat",sound:"crocodile"),
        Quiz(answer:"flog",section1:"_fish", section2:"flog",section3:"fox",sound:"flog"),
        Quiz(answer:"lobster",section1:"lion", section2:"chick",section3:"lobster",sound:"lobster"),
        Quiz(answer:"starfish",section1:"starfish", section2:"penguin",section3:"dolphin",sound:"starfish"),
    ],[
        Quiz(answer:"ant",section1:"tiger", section2:"ant",section3:"butterfly",sound:"ant"),
        Quiz(answer:"bee",section1:"ant", section2:"bird",section3:"bee",sound:"bee"),
        Quiz(answer:"beetle",section1:"beetle", section2:"bee",section3:"butterfly",sound:"beetle"),
        Quiz(answer:"butterfly",section1:"bee", section2:"butterfly",section3:"beetle",sound:"butterfly"),
        Quiz(answer:"caterpillar",section1:"crow", section2:"octopus",section3:"caterpillar",sound:"caterpillar"),
        Quiz(answer:"dragonfly",section1:"dragonfly", section2:"dog",section3:"duck",sound:"dragonfly"),
        Quiz(answer:"ladybug",section1:"butterfly", section2:"ladybug",section3:"motorcycle",sound:"ladybug"),
        Quiz(answer:"snail",section1:"starfish", section2:"koala",section3:"snail",sound:"snail"),
        ],[
        Quiz(answer:"autumn leaves",section1:"autumn leaves", section2:"ant",section3:"sheep",sound:"autumn leaves"),
        Quiz(answer:"bamboo",section1:"ladybug", section2:"bamboo",section3:"dragonfly",sound:"bamboo"),
        Quiz(answer:"carnation",section1:"crow", section2:"cat",section3:"carnation",sound:"carnation"),
        Quiz(answer:"cherry blossoms",section1:"cherry blossoms", section2:"peach blossoms",section3:"cherries",sound:"cherry blossoms"),
        Quiz(answer:"iris",section1:"beetle", section2:"iris",section3:"leaf",sound:"iris"),
        Quiz(answer:"leaf",section1:"lion", section2:"wolf",section3:"leaf",sound:"leaf"),
        Quiz(answer:"lily",section1:"lily", section2:"flying_fish",section3:"tree",sound:"lily"),
        Quiz(answer:"morning glory",section1:"mouse", section2:"morning glory",section3:"bamboo",sound:"morning glory"),
    ],[
        Quiz(answer:"peach blossoms",section1:"autumn leaves", section2:"truck",section3:"peach blossoms",sound:"peach blossoms"),
        Quiz(answer:"rose",section1:"rose", section2:"rabbit",section3:"peach blossoms",sound:"rose"),
        Quiz(answer:"sunflower",section1:"carnation", section2:"sunflower",section3:"morning glory",sound:"sunflower"),
        Quiz(answer:"tree",section1:"sunflower", section2:"tulip",section3:"tree",sound:"tree"),
        Quiz(answer:"tulip",section1:"tulip", section2:"tree",section3:"butterfly",sound:"tulip"),
        Quiz(answer:"dandelion",section1:"sunflower", section2:"dandelion",section3:"peach blossoms",sound:"dandelion"),
    ]
        ],
//        周りにあるもの
    [[
        Quiz(answer:"airplane",section1:"ant", section2:"ambulance",section3:"airplane",sound:"airplane"),
        Quiz(answer:"ambulance",section1:"ambulance", section2:"fire engine",section3:"umbrella",sound:"ambulance"),
        Quiz(answer:"bicycle",section1:"ship", section2:"bicycle",section3:"police car",sound:"bicycle"),
        Quiz(answer:"boat",section1:"truck", section2:"bus",section3:"boat",sound:"boat"),
        Quiz(answer:"bus",section1:"bus", section2:"bicycle",section3:"car",sound:"bus"),
        Quiz(answer:"car",section1:"bicycle", section2:"car",section3:"bus",sound:"car"),
        Quiz(answer:"fire engine",section1:"helicopter", section2:"ambulance",section3:"fire engine",sound:"fire engine"),
        Quiz(answer:"helicopter",section1:"helicopter", section2:"bicycle",section3:"motorcycle",sound:"helicopter"),
        Quiz(answer:"motorcycle",section1:"bicycle", section2:"motorcycle",section3:"subway",sound:"motorcycle"),
    ],[
        Quiz(answer:"ship",section1:"ambulance", section2:"car",section3:"ship",sound:"ship"),
        Quiz(answer:"space shuttle",section1:"space shuttle", section2:"subway",section3:"helicopter",sound:"space shuttle"),
        Quiz(answer:"subway",section1:"train", section2:"truck",section3:"subway",sound:"subway"),
        Quiz(answer:"taxi",section1:"taxi", section2:"subway",section3:"police car",sound:"taxi"),
        Quiz(answer:"train",section1:"taxi", section2:"train",section3:"bus",sound:"train"),
        Quiz(answer:"truck",section1:"bookstore", section2:"yacht",section3:"truck",sound:"truck"),
        Quiz(answer:"yacht",section1:"yacht", section2:"space shuttle",section3:"subway",sound:"yacht"),
        Quiz(answer:"police car",section1:"helicopter", section2:"police car",section3:"pastry shop",sound:"police car"),
    ],[
        Quiz(answer:"airport",section1:"airplane", section2:"apple",section3:"airport",sound:"airport"),
        Quiz(answer:"amusement park",section1:"amusement park", section2:"_convenience store",section3:"supermarket",sound:"amusement park"),
        Quiz(answer:"aquarium",section1:"amusement park", section2:"aquarium",section3:"airport",sound:"aquarium"),
        Quiz(answer:"art museum",section1:"fire engine", section2:"bank",section3:"art museum",sound:"art museum"),
        Quiz(answer:"bakery",section1:"bakery", section2:"_fish shop",section3:"_flower shop",sound:"bakery"),
        Quiz(answer:"bank",section1:"bag", section2:"bank",section3:"bakery",sound:"bank"),
        Quiz(answer:"barbershop",section1:"baseball stadium", section2:"barbershop",section3:"_flower shop",sound:"barbershop"),
        Quiz(answer:"baseball stadium",section1:"baseball stadium", section2:"_flower shop",section3:"barbershop",sound:"baseball stadium"),
        Quiz(answer:"bookstore",section1:"_flower shop", section2:"bookstore",section3:"hotel",sound:"bookstore"),
    ],[
        Quiz(answer:"_building",section1:"_church", section2:"_department store",section3:"_building",sound:"_building"),
        Quiz(answer:"_bus stop",section1:"_bus stop", section2:"taxi",section3:"bicycle",sound:"_bus stop"),
        Quiz(answer:"_church",section1:"police car", section2:"_church",section3:"_convenience store",sound:"_church"),
        Quiz(answer:"_convenience store",section1:"pastry shop", section2:"station",section3:"_convenience store",sound:"_convenience store"),
        Quiz(answer:"_department store",section1:"_department store", section2:"baseball stadium",section3:"art museum",sound:"_department store"),
        Quiz(answer:"_drugstore",section1:"_church", section2:"_drugstore",section3:"aquarium",sound:"_drugstore"),
        Quiz(answer:"_fire stadium",section1:"_drugstore", section2:"airport",section3:"_fire stadium",sound:"_fire stadium"),
        Quiz(answer:"_fish shop",section1:"_fish shop", section2:"_fire stadium",section3:"toy shop",sound:"_fish shop"),
        Quiz(answer:"_flower shop",section1:"sunny", section2:"_flower shop",section3:"school",sound:"_flower shop"),
    ],[
        Quiz(answer:"gas station",section1:"_church", section2:"_convenience store",section3:"gas station",sound:"gas station"),
        Quiz(answer:"hospital",section1:"hospital", section2:"park",section3:"_drugstore",sound:"hospital"),
        Quiz(answer:"hotel",section1:"hospital", section2:"hotel",section3:"movie theater",sound:"hotel"),
        Quiz(answer:"movie theater",section1:"fire engine", section2:"barbershop",section3:"movie theater",sound:"movie theater"),
        Quiz(answer:"nursery school",section1:"nursery school", section2:"traffic light",section3:"station",sound:"nursery school"),
        Quiz(answer:"park",section1:"hospital", section2:"park",section3:"police box",sound:"park"),
        Quiz(answer:"pastry shop",section1:"_department store", section2:"yacht",section3:"pastry shop",sound:"pastry shop"),
        Quiz(answer:"police box",section1:"police box", section2:"_drugstore",section3:"aquarium",sound:"police box"),
    ],[
        Quiz(answer:"police station",section1:"vegetable shop", section2:"police station",section3:"supermarket",sound:"police station"),
        Quiz(answer:"post office",section1:"police station", section2:"school",section3:"post office",sound:"post office"),
        Quiz(answer:"restaurant",section1:"restaurant", section2:"amusement park",section3:"_drugstore",sound:"restaurant"),
        Quiz(answer:"school",section1:"subway", section2:"school",section3:"police car",sound:"school"),
        Quiz(answer:"shoe shop",section1:"hotel", section2:"bakery",section3:"shoe shop",sound:"shoe shop"),
        Quiz(answer:"station",section1:"station", section2:"space shuttle",section3:"school",sound:"station"),
        Quiz(answer:"supermarket",section1:"shoe shop", section2:"supermarket",section3:"pastry shop",sound:"supermarket"),
        Quiz(answer:"tower",section1:"_church", section2:"barbershop",section3:"tower",sound:"tower"),
        Quiz(answer:"toy shop",section1:"toy shop", section2:"movie theater",section3:"park",sound:"toy shop"),
    ],[
        Quiz(answer:"traffic light",section1:"train", section2:"traffic light",section3:"taxi",sound:"traffic light"),
        Quiz(answer:"vegetable shop",section1:"police station", section2:"_bus stop",section3:"vegetable shop",sound:"vegetable shop"),
        Quiz(answer:"zoo",section1:"zoo", section2:"barbershop",section3:"ambulance",sound:"zoo"),
        Quiz(answer:"_water fountain",section1:"airport", section2:"_water fountain",section3:"school",sound:"_water fountain"),
        Quiz(answer:"beach",section1:"bag", section2:"bakery",section3:"beach",sound:"beach"),
        Quiz(answer:"castle",section1:"castle", section2:"cat",section3:"restaurant",sound:"castle"),
        Quiz(answer:"mountain",section1:"castle", section2:"mountain",section3:"truck",sound:"mountain"),
        Quiz(answer:"pyramid",section1:"_fish shop", section2:"motorcycle",section3:"pyramid",sound:"pyramid"),
    ],[
        Quiz(answer:"apron",section1:"hat", section2:"apron", section3:"jacket",sound:"apron"),
        Quiz(answer:"belt",section1:"pants", section2:"dress", section3:"belt",sound:"belt"),
        Quiz(answer:"blouse",section1:"belt", section2:"cap", section3:"blouse",sound:"blouse"),
        Quiz(answer:"cap",section1:"cap", section2:"cup", section3:"water",sound:"cap"),
        Quiz(answer:"dress",section1:"dress", section2:"overcoat", section3:"socks",sound:"dress"),
        Quiz(answer:"gloves",section1:"green pepper", section2:"gloves", section3:"bag",sound:"gloves"),
        Quiz(answer:"hat",section1:"hat", section2:"straw hat", section3:"necktie",sound:"hat"),
        Quiz(answer:"jacket",section1:"jeans", section2:"skirt", section3:"jacket",sound:"jacket"),
        Quiz(answer:"jeans",section1:"alarm clock", section2:"jeans", section3:"cell phone",sound:"jeans"),
        Quiz(answer:"overcoat",section1:"overcoat", section2:"mirror", section3:"T-shirt",sound:"overcoat"),
        Quiz(answer:"pajamas",section1:"pear", section2:"pajamas", section3:"pants",sound:"pajamas"),
        Quiz(answer:"pants",section1:"magazine", section2:"telephone", section3:"pants",sound:"pants"),
        ],[
        Quiz(answer:"raincoat",section1:"raincoat", section2:"cabbage", section3:"curry and rice",sound:"raincoat"),
        Quiz(answer:"shirt",section1:"shoes", section2:"shorts",  section3:"shirt",sound:"shirt"),
        Quiz(answer:"shoes",section1:"shorts", section2:"shoes", section3:"shirt",sound:"shoes"),
        Quiz(answer:"shorts",section1:"shorts", section2:"shirt", section3:"shoes",sound:"shorts"),
        Quiz(answer:"skirt",section1:"skirt", section2:"calender", section3:"medicine",sound:"skirt"),
        Quiz(answer:"sneakers",section1:"broom", section2:"sneakers", section3:"brush",sound:"sneakers"),
        Quiz(answer:"socks",section1:"guitar", section2:"socks", section3:"umbrella",sound:"socks"),
        Quiz(answer:"straw hat",section1:"straw hat", section2:"newspaper", section3:"pickles",sound:"straw hat"),
        Quiz(answer:"sweater",section1:"swimsuit", section2:"miso soup", section3:"sweater",sound:"sweater"),
        Quiz(answer:"swimsuit",section1:"cheese", section2:"swimsuit", section3:"swimming pool",sound:"swimsuit"),
        Quiz(answer:"T-shirt",section1:"T-shirt", section2:"door", section3:"picture",sound:"T-shirt"),
        Quiz(answer:"necktie",section1:"brush my teeth", section2:"zero", section3:"necktie",sound:"necktie"),
        ],[
        Quiz(answer:"alarm clock",section1:"apple", section2:"sausage", section3:"alarm clock",sound:"alarm clock"),
        Quiz(answer:"backpack",section1:"salt", section2:"backpack", section3:"egg",sound:"backpack"),
        Quiz(answer:"bag",section1:"bag", section2:"wine", section3:"cake",sound:"bag"),
        Quiz(answer:"broom",section1:"bag", section2:"broom",  section3:"fork",sound:"broom"),
        Quiz(answer:"brush",section1:"coffee", section2:"towel",  section3:"brush",sound:"brush"),
        Quiz(answer:"calender",section1:"calender", section2:"bibimbap",  section3:"cap",sound:"calendar"),
        Quiz(answer:"camera",section1:"cap", section2:"camera",  section3:"cell phone",sound:"camera"),
        Quiz(answer:"cell phone",section1:"steak", section2:"PC",  section3:"cell phone",sound:"cell phone"),
        Quiz(answer:"clock",section1:"clock", section2:"cap",  section3:"cup",sound:"clock"),
        Quiz(answer:"glasses",section1:"grapes", section2:"glasses",  section3:"grapefruit",sound:"glasses"),
        Quiz(answer:"glove",section1:"pepper", section2:"pizza", section3:"glove",sound:"glove"),
        Quiz(answer:"guitar",section1:"guitar", section2:"yogurt",  section3:"pillow",sound:"guitar"),
        ],[
        Quiz(answer:"magazine",section1:"apron", section2:"magazine", section3:"soba noodle",sound:"magazine"),
        Quiz(answer:"medicine",section1:"melon", section2:"potato", section3:"medicine",sound:"medicine"),
        Quiz(answer:"mirror",section1:"mirror", section2:"raincoat", section3:"television",sound:"mirror"),
        Quiz(answer:"newspaper",section1:"mushroom", section2:"newspaper", section3:"soy sauce",sound:"newspaper"),
        Quiz(answer:"PC",section1:"pants", section2:"belt", section3:"PC",sound:"PC"),
        Quiz(answer:"pillow",section1:"pillow", section2:"pear", section3:"camera",sound:"pillow"),
        Quiz(answer:"telephone",section1:"corn", section2:"telephone", section3:"cereal",sound:"telephone"),
        Quiz(answer:"television",section1:"watch", section2:"carrot", section3:"television",sound:"television"),
        Quiz(answer:"towel",section1:"towel", section2:"Japanese radish", section3:"croissant",sound:"towel"),
        Quiz(answer:"umbrella",section1:"bread", section2:"umbrella", section3:"mirror",sound:"umbrella"),
        Quiz(answer:"watch",section1:"_fish", section2:"lettuce", section3:"watch",sound:"watch"),
        Quiz(answer:"comic",section1:"comic", section2:"hotdog", section3:"corn",sound:"comic"),
    ],
//    前置詞はここに入れる予定
    [          Quiz(answer:"prepositionAt",section1:"prepositionAt", section2:"prepositionOn", section3:"prepositionNear", sound:"AtSound"),
               Quiz(answer:"prepositionOver",section1:"prepositionFor", section2:"prepositionOver", section3:"prepositionUnder", sound:"OverSound"),
               Quiz(answer:"prepositionIn",section1:"prepositionUnder", section2:"prepositionFrom", section3:"prepositionIn", sound:"InSound"),
               Quiz(answer:"prepositionOn",section1:"prepositionOn", section2:"prepositionAt", section3:"prepositionFrom", sound:"OnSound"),
               Quiz(answer:"prepositionUnder",section1:"prepositionBefore", section2:"prepositionUnder", section3:"prepositionWith", sound:"UnderSound"),
               Quiz(answer:"prepositionFrom",section1:"prepositionNear", section2:"prepositionOver", section3:"prepositionFrom", sound:"FromSound"),
               Quiz(answer:"prepositionBefore",section1:"prepositionBefore", section2:"prepositionFor", section3:"prepositionAt", sound:"BeforeSound"),
               Quiz(answer:"prepositionFor",section1:"prepositionWith", section2:"prepositionFor", section3:"prepositionUnder", sound:"ForSound"),
               Quiz(answer:"prepositionNear",section1:"prepositionAt", section2:"prepositionOn", section3:"prepositionNear", sound:"NearSound"),
               Quiz(answer:"prepositionWith",section1:"prepositionWith", section2:"prepositionOn", section3:"prepositionAt", sound:"WithSound"),]
    ],
//        学校
        [[
            Quiz(answer:"arts and crafts",section1:"lunch", section2:"calligraphy",section3:"arts and crafts",sound:"arts and crafts"),
            Quiz(answer:"calligraphy",section1:"calligraphy", section2:"English",section3:"home economics",sound:"calligraphy"),
            Quiz(answer:"English",section1:"japanese", section2:"English",section3:"music",sound:"English"),
            Quiz(answer:"japanese",section1:"English", section2:"music",section3:"japanese",sound:"japanese"),
            Quiz(answer:"math",section1:"math", section2:"science",section3:"recess",sound:"math"),
            Quiz(answer:"moral education",section1:"math", section2:"moral education",section3:"PE",sound:"moral education"),
            Quiz(answer:"music",section1:"PE", section2:"arts and crafts",section3:"music",sound:"music"),
            Quiz(answer:"PE",section1:"PE", section2:"playground",section3:"library",sound:"PE"),
            Quiz(answer:"recess",section1:"social studies", section2:"recess",section3:"moral education",sound:"recess"),
            Quiz(answer:"science",section1:"shoes box", section2:"_fish tank",section3:"science",sound:"science"),
            Quiz(answer:"social studies",section1:"social studies", section2:"science room",section3:"soccer ball",sound:"social studies"),
            Quiz(answer:"home economics",section1:"home economics", section2:"gym",section3:"English",sound:"home economics"),
            Quiz(answer:"lunch",section1:"library", section2:"entrance ceremony",section3:"lunch",sound:"lunch"),
        ],[
            Quiz(answer:"ball",section1:"basketball", section2:"blackboard",section3:"ball",sound:"ball"),
            Quiz(answer:"basketball",section1:"black", section2:"bathroom",section3:"basketball",sound:"basketball"),
            Quiz(answer:"blackboard",section1:"blackboard", section2:"brown",section3:"bookshelf",sound:"blackboard"),
            Quiz(answer:"bookshelf",section1:"ball", section2:"bookshelf",section3:"blackboard",sound:"bookshelf"),
            Quiz(answer:"chair",section1:"square", section2:"chalk",section3:"chair",sound:"chair"),
            Quiz(answer:"chalk",section1:"chalk", section2:"science",section3:"chair",sound:"chalk"),
            Quiz(answer:"desk",section1:"playground", section2:"desk",section3:"swimming pool",sound:"desk"),
            Quiz(answer:"eraser",section1:"lunch", section2:"map",section3:"eraser",sound:"eraser"),
        ],[
            Quiz(answer:"_fish tank",section1:"_fish tank", section2:"field trip",section3:"_teachers room",sound:"_fish tank"),
            Quiz(answer:"globe",section1:"gray", section2:"globe",section3:"green",sound:"globe"),
            Quiz(answer:"jump rope",section1:"computer room", section2:"bookshelf",section3:"jump rope",sound:"jump rope"),
            Quiz(answer:"map",section1:"map", section2:"heart",section3:"math",sound:"map"),
            Quiz(answer:"piano",section1:"pink", section2:"piano",section3:"pig",sound:"piano"),
            Quiz(answer:"picture",section1:"pink", section2:"pig",section3:"picture",sound:"picture"),
            Quiz(answer:"soccer ball",section1:"soccer ball", section2:"summer vacation",section3:"student",sound:"soccer ball"),
            Quiz(answer:"wastebasket",section1:"water fountain", section2:"wastebasket",section3:"classroom",sound:"wastebasket"),
        ],[
            Quiz(answer:"principal",section1:"English", section2:"entrance ceremony",section3:"principal",sound:"principal"),
            Quiz(answer:"student",section1:"summer vacation", section2:"principal",section3:"student",sound:"student"),
            Quiz(answer:"_teacher",section1:"_teacher", section2:"student",section3:"field trip",sound:"_teacher"),
            Quiz(answer:"entrance ceremony",section1:"student", section2:"entrance ceremony",section3:"sports day",sound:"entrance ceremony"),
            Quiz(answer:"field trip",section1:"student", section2:"_teacher",section3:"field trip",sound:"field trip"),
            Quiz(answer:"sports day",section1:"sports day", section2:"student",section3:"field trip",sound:"sports day"),
            Quiz(answer:"summer vacation",section1:"student", section2:"summer vacation",section3:"social studies",sound:"summer vacation"),
        ],
//        削除　学用品
//        [
//            Quiz(answer:"arts",section1:"red", section2:"bookshelf",section3:"arts",sound:"arts"),
//            Quiz(answer:"bathroom",section1:"bathroom", section2:"blackboard",section3:"basketball",sound:"bathroom"),
//            Quiz(answer:"classroom",section1:"computer room", section2:"classroom",section3:"shoes box",sound:"classroom"),
//            Quiz(answer:"computer room",section1:"water fountain", section2:"music room",section3:"computer room",sound:"computer room"),
//            Quiz(answer:"door",section1:"door", section2:"map",section3:"_fish tank",sound:"door"),
//            Quiz(answer:"gym",section1:"gray", section2:"gym",section3:"green",sound:"gym"),
//            Quiz(answer:"library",section1:"lunch", section2:"recess",section3:"library",sound:"library"),
//            Quiz(answer:"music room",section1:"music room", section2:"classroom",section3:"sports day",sound:"music room"),
//        ],[
//            Quiz(answer:"nurse’s office",section1:"nurse’s office", section2:"desk",section3:"science room",sound:"nurse’s office"),
//            Quiz(answer:"playground",section1:"science room", section2:"playground",section3:"wastebasket",sound:"playground"),
//            Quiz(answer:"science room",section1:"chalk", section2:"arts and crafts room",section3:"science room",sound:"science room"),
//            Quiz(answer:"shoe box",section1:"shoe box", section2:"wastebasket",section3:"jump rope",sound:"shoe box"),
//            Quiz(answer:"swimming pool",section1:"student", section2:"swimming pool",section3:"globe",sound:"swimming pool"),
//            Quiz(answer:"teachers’ room",section1:"classroom", section2:"music room",section3:"teachers’ room",sound:"teachers’ room"),
//            Quiz(answer:"water fountain",section1:"water fountain", section2:"window",section3:"nurse’s office",sound:"water fountain"),
//            Quiz(answer:"window",section1:"door", section2:"window",section3:"music room",sound:"window"),
//        ]
//        学校施設追加
        
        ],
//        お仕事
        [[
        Quiz(answer:"actor",section1:"fire fighter", section2:"dentist", section3:"actor",sound:"actor"),
        Quiz(answer:"artist",section1:"artist", section2:"dancer", section3:"singer",sound:"artist"),
        Quiz(answer:"astronaut",section1:"apple", section2:"astronaut", section3:"artist",sound:"astronaut"),
        Quiz(answer:"baker",section1:"bag", section2:"comedian", section3:"baker",sound:"baker"),
        Quiz(answer:"barber",section1:"barber", section2:"fisherman", section3:"model",sound:"barber"),
        Quiz(answer:"_baseball player",section1:"_cook", section2:"_baseball player", section3:"golf player",sound:"_baseball player"),
        Quiz(answer:"bride",section1:"bridegroom", section2:"mushroom", section3:"bride",sound:"bride"),
    ],[
        Quiz(answer:"bridegroom",section1:"bridegroom", section2:"hairdresser", section3:"tennis player",sound:"bridegroom"),
        Quiz(answer:"builder",section1:"vet", section2:"builder", section3:"scientist",sound:" builder"),
        Quiz(answer:"carpenter",section1:"comedian", section2:"cartoonist", section3:"carpenter",sound:"carpenter"),
        Quiz(answer:"cartoonist",section1:"cartoonist", section2:"computer programmer", section3:"photographer",sound:"cartoonist"),
        Quiz(answer:"comedian",section1:"comic", section2:"comedian", section3:"builder",sound:"comedian"),
        Quiz(answer:"computer programmer",section1:"nurse", section2:"pastry chef", section3:"computer programmer",sound:"computer programmer"),
        Quiz(answer:"_cook",section1:"_cook", section2:"computer programmer", section3:"artist",sound:"_cook"),
    ],[
        Quiz(answer:"dancer",section1:"dentist", section2:"dancer",  section3:"designer",sound:"dancer"),
        Quiz(answer:"dentist",section1:"designer", section2:"doctor", section3:"dentist",sound:"dentist"),
        Quiz(answer:"designer",section1:"designer", section2:"dentist", section3:"doctor",sound:"designer"),
        Quiz(answer:"engineer",section1:"egg", section2:"engineer", section3:"_teacher",sound:"engineer"),
        Quiz(answer:"farmer",section1:"jellyfish", section2:"family", section3:"farmer",sound:"farmer"),
        Quiz(answer:"fire fighter",section1:"fire fighter", section2:"mailman", section3:"cartoonist",sound:"fire fighter"),
        Quiz(answer:"doctor",section1:"doctor", section2:"baseball player", section3:"actor",sound:"doctor"),
    ],[
        Quiz(answer:"florist",section1:"little sister", section2:"florist", section3:"_fish",sound:"florist"),
        Quiz(answer:"golf player",section1:"doctor", section2:"dentist", section3:"golf player",sound:"golf player"),
        Quiz(answer:"hairdresser",section1:"hairdresser", section2:"barber", section3:"artist",sound:"hairdresser"),
        Quiz(answer:"journalist",section1:"bridegroom", section2:"journalist", section3:"zookeeper",sound:"journalist"),
        Quiz(answer:"lawyer",section1:"fire fighter", section2:"journalist", section3:"lawyer",sound:"lawyer"),
        Quiz(answer:"mailman",section1:"mailman", section2:"baker", section3:"model",sound:"mailman"),
        Quiz(answer:"model",section1:"fisherman", section2:"model", section3:"barber",sound:"model"),
    ],[
        Quiz(answer:"nurse",section1:"pianist", section2:"model", section3:"nurse",sound:"nurse"),
        Quiz(answer:"pastry chef",section1:"pastry chef", section2:"carpenter", section3:"_cook",sound:"pastry chef"),
        Quiz(answer:"photographer",section1:"astronaut", section2:"photographer", section3:"actor",sound:"photographer"),
        Quiz(answer:"pianist",section1:"astronaut", section2:"dentist", section3:"pianist",sound:"pianist"),
        Quiz(answer:"pilot",section1:"pilot", section2:"photographer", section3:"zookeeper",sound:"pilot"),
        Quiz(answer:"police officer",section1:"soccer player", section2:"police officer",section3:"builder",sound:"police officer"),
        Quiz(answer:"scientist",section1:"soccer player", section2:"singer",section3:"scientist",sound:"scientist"),
    ],[
        Quiz(answer:"singer",section1:"singer", section2:"soccer player",section3:"_teacher",sound:"singer"),
        Quiz(answer:"soccer player",section1:"scientist", section2:"soccer player",section3:"tennis player",sound:"soccer player"),
        Quiz(answer:"_teacher",section1:"singer", section2:"tennis player",section3:"_teacher",sound:"_teacher"),
        Quiz(answer:"tennis player",section1:"tennis player", section2:"designer",section3:"mailman",sound:"tennis player"),
        Quiz(answer:"vet",section1:"vet", section2:"scientist",section3:"baker",sound:"vet"),
        Quiz(answer:"zookeeper",section1:"artist", section2:"zookeeper",section3:"nurse",sound:"zookeeper"),
        Quiz(answer:"fisherman",section1:"photographer", section2:"pilot",section3:"fisherman",sound:"fisherman"),
    ]
        ],
//        自然
        [[
        Quiz(answer:"black",section1:"blue", section2:"black",section3:"yellow",sound:"black"),
        Quiz(answer:"blue",section1:"black", section2:"brown",section3:"blue",sound:"blue"),
        Quiz(answer:"brown",section1:"brown", section2:"black",section3:"blue",sound:"brown"),
        Quiz(answer:"gray",section1:"green", section2:"gray",section3:"purple",sound:"gray"),
        Quiz(answer:"green",section1:"gray", section2:"orange",section3:"green",sound:"green"),
        Quiz(answer:"orange",section1:"orange", section2:"black",section3:"blue",sound:"orange"),
        Quiz(answer:"pink",section1:"purple", section2:"pink",section3:"green",sound:"pink"),
        Quiz(answer:"purple",section1:"green", section2:"red",section3:"purple",sound:"purple"),
        Quiz(answer:"red",section1:"red", section2:"gray",section3:"yellow",sound:"red"),
        Quiz(answer:"yellow",section1:"circle", section2:"yellow",section3:"gray",sound:"yellow"),
    ],

    [
        Quiz(answer:"rainy season",section1:"rainy season", section2:"windy",section3:"summer",sound:"rainy season"),
        Quiz(answer:"spring",section1:"summer", section2:"spring",section3:"winter",sound:"spring"),
        Quiz(answer:"fall",section1:"winter", section2:"summer",section3:"fall",sound:"fall"),
        Quiz(answer:"summer",section1:"summer", section2:"snowy",section3:"windy",sound:"summer"),
        Quiz(answer:"winter",section1:"rainy", section2:"winter",section3:"_hot",sound:"winter"),
    ],[
        //    ここに天気
        Quiz(answer:"cloudy",section1:"cloudy", section2:"windy", section3:"snowy",sound:"cloudy.mp3"),
        Quiz(answer:"cold",section1:"rainy", section2:"cold", section3:"cloudy",sound:"cold.mp3"),
        Quiz(answer:"_hot",section1:"cold", section2:"sunny", section3:"_hot",sound:"_hot.mp3"),
        Quiz(answer:"rainy",section1:"snowy", section2:"windy", section3:"rainy",sound:"rainy.mp3"),
        Quiz(answer:"snowy",section1:"sunny", section2:"snowy", section3:"windy",sound:"snowy.mp3"),
        Quiz(answer:"sunny",section1:"windy", section2:"snowy", section3:"sunny",sound:"sunny.mp3"),
        Quiz(answer:"warm",section1:"warm", section2:"sunny", section3:"cold",sound:"warm.mp3"),
        Quiz(answer:"windy",section1:"snowy", section2:"windy", section3:"rainy",sound:"windy.mp3"),
        ]
        ],
//        人と生活
        [[
            Quiz(answer:"big brother",section1:"big brother", section2:"family",section3:"big sister",sound:"big brother"),
            Quiz(answer:"big sister",section1:"big brother", section2:"big sister",section3:"grandfather",sound:"big sister"),
            Quiz(answer:"family",section1:"family", section2:"grandfather",section3:"big sister",sound:"family"),
            Quiz(answer:"father",section1:"family", section2:"father",section3:"grandfather",sound:"father"),
            Quiz(answer:"grandfather",section1:"father", section2:"grandmother",section3:"grandfather",sound:"grandfather"),
            Quiz(answer:"grandmother",section1:"grandmother", section2:"grandfather",section3:"father",sound:"grandmother"),
            Quiz(answer:"little brother",section1:"little sister", section2:"little brother",section3:"mother",sound:"little brother"),
            Quiz(answer:"little sister",section1:"family", section2:"little brother",section3:"little sister",sound:"little sister"),
            Quiz(answer:"mother",section1:"mother", section2:"grandmother",section3:"family",sound:"mother"),
       ],[
        Quiz(answer:"bean scattering",section1:"bathroom", section2:"bean scattering",section3:"bookshelf",sound:"bean scattering"),
        Quiz(answer:"birthday",section1:"bookshelf", section2:"black",section3:"birthday",sound:"birthday"),
        Quiz(answer:"bon dance",section1:"enjoying cherry blossoms", section2:"bon dance",section3:"basketball",sound:"bon dance"),
        Quiz(answer:"children’s day",section1:"chalk", section2:"chair",section3:"children’s day",sound:"children’s day"),
        Quiz(answer:"Chinese New Year",section1:"Chinese New Year", section2:"chair",section3:"bathroom",sound:"Chinese New Year"),
        Quiz(answer:"doll’s festival",section1:"summer vacation", section2:"doll’s festival",section3:"calligraphy",sound:"doll’s festival"),
        Quiz(answer:"enjoying cherry blossoms",section1:"field trip", section2:"wastebasket",section3:"enjoying cherry blossoms",sound:"enjoying cherry blossoms"),
        Quiz(answer:"enjoying the full moon",section1:"enjoying the full moon", section2:"enjoying cherry blossoms",section3:"fireworks",sound:"enjoying the full moon"),
        Quiz(answer:"fireworks",section1:"_fish tank", section2:"fireworks",section3:"picture",sound:"fireworks"),
        Quiz(answer:"Halloween",section1:"computer room", section2:"Christmas",section3:"Halloween",sound:"Halloween"),
        Quiz(answer:"New Year’s Day",section1:"New Year’s Day", section2:"Christmas",section3:"children’s day",sound:"New Year’s Day"),
        Quiz(answer:"New Year’s Eve",section1:"children’s day", section2:"New Year’s Eve",section3:"doll’s festival",sound:"New Year’s Eve"),
        Quiz(answer:"star festival",section1:"red", section2:"social studies",section3:"star festival",sound:"star festival"),
        Quiz(answer:"Christmas",section1:"Christmas", section2:"chair",section3:"birthday",sound:"Christmas"),
    ],[
        Quiz(answer:"angry",section1:"angry", section2:"ant",section3:"tired",sound:"angry"),
        Quiz(answer:"bored",section1:"bread", section2:"bored",section3:"bird",sound:"bored"),
        Quiz(answer:"busy",section1:"big", section2:"bag",section3:"busy",sound:"busy"),
        Quiz(answer:"fine",section1:"fine", section2:"_full",section3:"fly",sound:"fine"),
        Quiz(answer:"_full",section1:"fine", section2:"_full",section3:"small",sound:"_full"),
        Quiz(answer:"happy",section1:"angry", section2:"good",section3:"happy",sound:"happy"),
        Quiz(answer:"hungry",section1:"hungry", section2:"_full",section3:"humbergur",sound:"hungry"),
        Quiz(answer:"sad",section1:"sick", section2:"sad",section3:"fine",sound:"sad"),
        Quiz(answer:"sick",section1:"kick", section2:"good",section3:"sick",sound:"sick"),
        Quiz(answer:"sleepy",section1:"sleepy", section2:"happy",section3:"tomato",sound:"sleepy"),
        Quiz(answer:"thirsty",section1:"thirteen", section2:"thirsty",section3:"thirty",sound:"thirsty"),
        Quiz(answer:"tired",section1:"necktie", section2:"sick",section3:"tired",sound:"tired"),
    ]
    ],
//      旅
        [[
        Quiz(answer:"north",section1:"north", section2:"south",section3:"west",sound:"north"),
        Quiz(answer:"south",section1:"west", section2:"south",section3:"east",sound:"south"),
        Quiz(answer:"west",section1:"east", section2:"south",section3:"west",sound:"west"),
        Quiz(answer:"east",section1:"east", section2:"south",section3:"north",sound:"east"),
    ],[
        Quiz(answer:"Australia",section1:"Mexico", section2:"Australia",section3:"Canada",sound:"Australia"),
        Quiz(answer:"Brazil",section1:"Germany", section2:"India",section3:"Brazil",sound:"Brazil"),
        Quiz(answer:"Canada",section1:"Canada", section2:"Ecuador",section3:"Egypt",sound:"Canada"),
        Quiz(answer:"China",section1:"Norway", section2:"China",section3:"Kenya",sound:"China"),
        Quiz(answer:"Ecuador",section1:"Mexico", section2:"Greece",section3:"Ecuador",sound:"Ecuador"),
        Quiz(answer:"Egypt",section1:"Egypt", section2:"Korea",section3:"New Zealand",sound:"Egypt"),
        Quiz(answer:"England",section1:"Saudi Arabia", section2:"England",section3:"India",sound:"England"),
        Quiz(answer:"France",section1:"Mexico", section2:"Australia",section3:"France",sound:"France"),
        Quiz(answer:"Germany",section1:"Germany", section2:"Singapore",section3:"Thailand",sound:"Germany"),
        Quiz(answer:"Greece",section1:"Mexico", section2:"Greece",section3:"New Zealand",sound:"Greece"),
        Quiz(answer:"India",section1:"New Zealand", section2:"China",section3:"India",sound:"India"),
        Quiz(answer:"Italy",section1:"Italy", section2:"Mexico",section3:"France",sound:"Italy"),
        Quiz(answer:"India",section1:"New Zealand", section2:"India",section3:"France",sound:"India"),
    ],[
        Quiz(answer:"Japan",section1:"Egypt", section2:"England",section3:"Japan",sound:"Japan"),
        Quiz(answer:"Kenya",section1:"Kenya", section2:"China",section3:"Italy",sound:"Kenya"),
        Quiz(answer:"Korea",section1:"Norway", section2:"Korea",section3:"The United States",sound:"Korea"),
        Quiz(answer:"Mexico",section1:"Germany", section2:"Egypt",section3:"Mexico",sound:"Mexico"),
        Quiz(answer:"New Zealand",section1:"New Zealand", section2:"Spain",section3:"Ecuador",sound:"New Zealand"),
        Quiz(answer:"Norway",section1:"Greece", section2:"Norway",section3:"Russia",sound:"Norway"),
        Quiz(answer:"Saudi Arabia",section1:"Italy", section2:"Thailand",section3:"Saudi Arabia",sound:"Saudi Arabia"),
        Quiz(answer:"Singapore",section1:"Singapore", section2:"New Zealand",section3:"Egypt",sound:"Singapore"),
        Quiz(answer:"Thailand",section1:"Russia", section2:"Thailand",section3:"New Zealand",sound:"Thailand"),
        Quiz(answer:"The United States",section1:"Brazil", section2:"Egypt",section3:"The United States",sound:"The United States"),
        Quiz(answer:"Spain",section1:"Spain", section2:"Singapore",section3:"Spain",sound:"Spain"),
        Quiz(answer:"Russia",section1:"Mexico", section2:"Russia",section3:"England",sound:"Russia"),
    ],[
        Quiz(answer:"bean bag",section1:"bean bag", section2:"nursery school",section3:"mountain",sound:"bean bag"),
        Quiz(answer:"flower arrangement",section1:"_flower shop", section2:"flower arrangement",section3:"_convenience store",sound:"flower arrangement"),
        Quiz(answer:"folding fan",section1:"vegetable shop", section2:"temple",section3:"folding fan",sound:"folding fan"),
        Quiz(answer:"shrine",section1:"shrine", section2:"zoo",section3:"_bus stop",sound:"shrine"),
        Quiz(answer:"tea ceremony",section1:"pastry shop", section2:"tea ceremony",section3:"police box",sound:"tea ceremony"),
        Quiz(answer:"temple",section1:"bank", section2:"bookstore",section3:"temple",sound:"temple"),
    ]
        ],
//        時間
        [[
            Quiz(answer:"later",section1:"later", section2:"today",section3:"Monday",sound:"later"),
            Quiz(answer:"yesterday",section1:"Saturday", section2:"yesterday",section3:"December",sound:"yesterday"),
            Quiz(answer:"today",section1:"Friday", section2:"Monday",section3:"today",sound:"today"),
            Quiz(answer:"day after tomorrow",section1:"day after tomorrow", section2:"Friday",section3:"today",sound:"day after tomorrow"),
        ],[
        Quiz(answer:"Sunday",section1:"yesterday", section2:"Monday",section3:"Sunday",sound:"Sunday"),
        Quiz(answer:"Monday",section1:"Monday", section2:"Wednesday",section3:"Friday",sound:"Monday"),
        Quiz(answer:"Tuesday",section1:"Wednesday", section2:"Tuesday",section3:"Saturday",sound:"Tuesday"),
        Quiz(answer:"Wednesday",section1:"Sunday", section2:"Tuesday",section3:"Wednesday",sound:"Wednesday"),
        Quiz(answer:"Thursday",section1:"Thursday", section2:"Tuesday",section3:"Friday",sound:"Thursday"),
        Quiz(answer:"Friday",section1:"Saturday", section2:"Friday",section3:"Sunday",sound:"Friday"),
        Quiz(answer:"Saturday",section1:"Tuesday", section2:"Thursday",section3:"Saturday",sound:"Saturday"),
    ],[
            Quiz(answer:"January",section1:"yesterday", section2:"Japan",section3:"January",sound:"January"),
            Quiz(answer:"February",section1:"February", section2:"December",section3:"November",sound:"February"),
            Quiz(answer:"March",section1:"May", section2:"March",section3:"winter",sound:"March"),
            Quiz(answer:"April",section1:"Australia", section2:"August",section3:"April",sound:"April"),
            Quiz(answer:"May",section1:"May", section2:"March",section3:"February",sound:"May"),
            Quiz(answer:"June",section1:"July", section2:"June",section3:"November",sound:"June"),
            Quiz(answer:"July",section1:"June", section2:"August",section3:"July",sound:"July"),
            Quiz(answer:"August",section1:"August", section2:"January",section3:"February",sound:"August"),
            Quiz(answer:"September",section1:"summer", section2:"September",section3:"fall",sound:"September"),
            Quiz(answer:"October",section1:"November", section2:"September",section3:"October",sound:"October"),
            Quiz(answer:"November",section1:"November", section2:"March",section3:"May",sound:"November"),
            Quiz(answer:"December",section1:"November", section2:"December",section3:"October",sound:"December"),
        ]
],
//        算数
        [[
        Quiz(answer:"zero",section1:"three", section2:"ten",section3:"zero",sound:"zero"),
        Quiz(answer:"one",section1:"one", section2:"thirteen",section3:"ten",sound:"one"),
        Quiz(answer:"two",section1:"seven", section2:"two",section3:"three",sound:"two"),
        Quiz(answer:"three",section1:"thirty", section2:"sixteen",section3:"three",sound:"three"),
        Quiz(answer:"four",section1:"four", section2:"five",section3:"two",sound:"four"),
        Quiz(answer:"five",section1:"fifty", section2:"five",section3:"seventy",sound:"five"),
        Quiz(answer:"six",section1:"sixteen", section2:"ninety",section3:"six",sound:"six"),
        Quiz(answer:"seven",section1:"seven", section2:"seventeen",section3:"forty",sound:"seven"),
        Quiz(answer:"eight",section1:"seventy", section2:"eight",section3:"fifteen",sound:"eight"),
        Quiz(answer:"nine",section1:"thirteen", section2:"ninety",section3:"nine",sound:"nine"),
        Quiz(answer:"ten",section1:"ten", section2:"nine",section3:"eight",sound:"ten"),
    ],[
        Quiz(answer:"eleven",section1:"thirteen", section2:"eleven",section3:"one hundred",sound:"eleven"),
        Quiz(answer:"twelve",section1:"twenty", section2:"seventy",section3:"twelve",sound:"twelve"),
        Quiz(answer:"thirteen",section1:"thirteen", section2:"three",section3:"thirty",sound:"thirteen"),
        Quiz(answer:"fourteen",section1:"four", section2:"fourteen",section3:"forty",sound:"fourteen"),
        Quiz(answer:"fifteen",section1:"fifty", section2:"five",section3:"fifteen",sound:"fifteen"),
        Quiz(answer:"sixteen",section1:"sixteen", section2:"sixty",section3:"six",sound:"sixteen"),
        Quiz(answer:"seventeen",section1:"seventy", section2:"seventeen",section3:"seven",sound:"seventeen"),
        Quiz(answer:"eighteen",section1:"eight", section2:"eighty",section3:"eighteen",sound:"eighteen"),
        Quiz(answer:"nineteen",section1:"nineteen", section2:"nineteen",section3:"nine",sound:"nineteen"),
        Quiz(answer:"twenty",section1:"two", section2:"twenty",section3:"nine",sound:"twenty"),
        Quiz(answer:"thirty",section1:"three", section2:"thirteen",section3:"thirty",sound:"thirty"),
        Quiz(answer:"forty",section1:"forty", section2:"fourteen",section3:"four",sound:"forty"),
        Quiz(answer:"fifty",section1:"fifteen", section2:"fifty",section3:"five",sound:"fifty"),
        Quiz(answer:"sixty",section1:"six", section2:"sixteen",section3:"sixty",sound:"sixty"),
        Quiz(answer:"seventy",section1:"seventy", section2:"seven",section3:"seventeen",sound:"seventy"),
        Quiz(answer:"eighty",section1:"eight", section2:"eighty",section3:"eighteen",sound:"eighty"),
        Quiz(answer:"ninety",section1:"nine", section2:"nineteen",section3:"ninety",sound:"ninety"),
        Quiz(answer:"one hundred",section1:"one hundred", section2:"one",section3:"zero",sound:"one hundred"),
    ],[
        Quiz(answer:"circle",section1:"oval", section2:"circle",section3:"triangle",sound:"circle"),
        Quiz(answer:"diamond",section1:"blue", section2:"rectangle",section3:"diamond",sound:"diamond"),
        Quiz(answer:"heart",section1:"heart", section2:"gray",section3:"square",sound:"heart"),
        Quiz(answer:"oval",section1:"diamond", section2:"oval",section3:"_orange",sound:"oval"),
        Quiz(answer:"rectangle",section1:"heart", section2:"star",section3:"rectangle",sound:"rectangle"),
        Quiz(answer:"square",section1:"square", section2:"star",section3:"rectangle",sound:"square"),
        Quiz(answer:"star",section1:"brown", section2:"star",section3:"square",sound:"star"),
        Quiz(answer:"triangle",section1:"pink", section2:"oval",section3:"triangle",sound:"triangle"),
    ]
        ],
//        動詞
        [[
            Quiz(answer:"brush my teeth",section1:"brush my teeth", section2:"bean scattering",section3:"Halloween",sound:"brush my teeth"),
            Quiz(answer:"_clean",section1:"sports day", section2:"_clean",section3:"bathroom",sound:"_clean"),
            Quiz(answer:"do homework",section1:"fireworks", section2:"New Year’s Day", section3:"do homework",sound:"do homework"),
//            Quiz(answer:"eat breakfast",section1:"eat breakfast", section2:"bookshelf",section3:"soccer ball",sound:"eat breakfast"),
            Quiz(answer:"eat dinner",section1:"eat school lunch", section2:"eat dinner",section3:"brush my teeth",sound:"eat dinner"),
            Quiz(answer:"eat lunch",section1:"do homework", section2:"_clean",section3:"eat lunch",sound:"eat lunch"),
            Quiz(answer:"eat school lunch",section1:"eat school lunch", section2:"enjoying the full moon",section3:"get dressed",sound:"eat school lunch"),
            Quiz(answer:"get dressed",section1:"eat lunch", section2:"get dressed",section3:"eat breakfast",sound:"get dressed"),
            Quiz(answer:"get up",section1:"star festival", section2:"New Year’s Eve",section3:"get up",sound:"get up"),
            Quiz(answer:"go home",section1:"go home", section2:"go to bed",section3:"arts and crafts room",sound:"go home"),
        ],[
            Quiz(answer:"go to bed",section1:"get dressed", section2:"go to bed",section3:"star festival",sound:"go to bed"),
            Quiz(answer:"go to school",section1:"go to bed", section2:"eat dinner",section3:"go to school",sound:"go to school"),
            Quiz(answer:"play games",section1:"play games", section2:"go to school",section3:"enjoying the full moon",sound:"play games"),
            Quiz(answer:"sleep",section1:"eat dinner", section2:"sleep",section3:"go home",sound:"sleep"),
            Quiz(answer:"study",section1:"sleep", section2:"take a shower",section3:"study",sound:"study"),
            Quiz(answer:"take a bath",section1:"take a bath", section2:"wash my hands",section3:"watch TV",sound:"take a bath"),
            Quiz(answer:"take a shower",section1:"take a bath", section2:"take a shower",section3:"wash my face",sound:"take a shower"),
            Quiz(answer:"wash my face",section1:"play games", section2:"wastebasket",section3:"wash my face",sound:"wash my face"),
            Quiz(answer:"wash my hands",section1:"wash my hands", section2:"get dressed",section3:"playground",sound:"wash my hands"),
            Quiz(answer:"watch TV",section1:"blackboard", section2:"watch TV",section3:"_clean",sound:"watch TV"),
        ],[
            Quiz(answer:"play baseball",section1:"play games", section2:"play golf",section3:"play baseball",sound:"play baseball"),
            Quiz(answer:"play basketball",section1:"play basketball", section2:"play table tennis",section3:"Skate",sound:"play baseball"),
            Quiz(answer:"play golf",section1:"play dodgeball", section2:"play golf",section3:"play baseball",sound:"play golf"),
            Quiz(answer:"play soccer",section1:"play basketball", section2:"play baseball",section3:"play soccer",sound:"play soccer"),
            Quiz(answer:"play table tennis",section1:"play table tennis", section2:"play golf",section3:"ski",sound:"play table tennis"),
            Quiz(answer:"play tennis",section1:"ski", section2:"play tennis",section3:"ski",sound:"play tennis"),
            Quiz(answer:"play volleyball",section1:"play tennis", section2:"play soccer",section3:"play volleyball",sound:"play volleyball"),
            Quiz(answer:"Skate",section1:"Skate", section2:"ski",section3:"play volleyball",sound:"Skate"),
            Quiz(answer:"ski",section1:"swim", section2:"ski",section3:"Skate",sound:"ski"),
            Quiz(answer:"swim",section1:"Skate", section2:"ski",section3:"swim",sound:"swim"),
        ],[
            Quiz(answer:"play cards",section1:"play cards", section2:"play golf",section3:"play soccer",sound:"play cards"),
            Quiz(answer:"play catch",section1:"play soccer", section2:"play catch",section3:"play tennis",sound:"play catch"),
            Quiz(answer:"play dodgeball",section1:"take a bath", section2:"play baseball",section3:"play dodgeball",sound:"play dodgeball"),
            Quiz(answer:"play hide and seek",section1:"play hide and seek", section2:"play baseball",section3:"play volleyball",sound:"play hide and seek"),
            Quiz(answer:"play on the bar",section1:"Skate", section2:"play on the bar",section3:"play basketball",sound:"play on the bar"),
            Quiz(answer:"playontheswing",section1:"play dodgeball", section2:"playontheswing",section3:"play basketball",sound:"playontheswing"),
            Quiz(answer:"ride a bicycle",section1:"ride a bicycle", section2:"listen to music",section3:"play the piano",sound:"ride a bicycle"),
            Quiz(answer:"talkwithmyfriends",section1:"Sing", section2:"talkwithmyfriends",section3:"ride a bicycle",sound:"talk with my friends"),
        ],[
            Quiz(answer:"listen to music",section1:"talkwithmyfriends", section2:"play the violin",section3:"listen to music",sound:"listen to music"),
            Quiz(answer:"play the guitar",section1:"play the guitar", section2:"play the piano",section3:"play the violin",sound:"play the guitar"),
            Quiz(answer:"play the piano",section1:"play the violin", section2:"play the piano",section3:"Sing",sound:"play the piano"),
            Quiz(answer:"play the violin",section1:"Sing", section2:"play the piano",section3:"play the violin",sound:"play the violin"),
            Quiz(answer:"Sing",section1:"Sing", section2:"play the piano",section3:"swim",sound:"Sing"),
        ],[
            Quiz(answer:"buy",section1:"bag", section2:"buy",section3:"big",sound:"buy"),
            Quiz(answer:"catch",section1:"cat", section2:"cap",section3:"catch",sound:"catch"),
            Quiz(answer:"clap",section1:"clap", section2:"_clean",section3:"sick",sound:"clap"),
            Quiz(answer:"cook",section1:"happy", section2:"cook",section3:"Sing",sound:"_cook"),
            Quiz(answer:"cry",section1:"cook", section2:"_cut",section3:"cry",sound:"cry"),
            Quiz(answer:"_cut",section1:"_cut", section2:"cook",section3:"cry",sound:"_cut"),
            Quiz(answer:"dance",section1:"desk", section2:"dance",section3:"_dry",sound:"dance"),
            Quiz(answer:"draw",section1:"dance", section2:"_dry",section3:"draw",sound:"draw"),
            Quiz(answer:"_dry",section1:"_dry", section2:"dance",section3:"draw",sound:"_dry"),
            Quiz(answer:"fly",section1:"fine", section2:"fly",section3:"_full",sound:"fly"),
        ],[
            Quiz(answer:"jump",section1:"Japan", section2:"good",section3:"jump",sound:"jump"),
            Quiz(answer:"kick",section1:"kick", section2:"sick",section3:"cook",sound:"kick"),
            Quiz(answer:"laugh",section1:"lion", section2:"laugh",section3:"_clean",sound:"laugh"),
            Quiz(answer:"paint",section1:"picture", section2:"pajamas",section3:"paint",sound:"paint"),
            Quiz(answer:"read",section1:"read", section2:"red",section3:"strong",sound:"read"),
            Quiz(answer:"run",section1:"red", section2:"run",section3:"eat",sound:"run"),
            Quiz(answer:"throw",section1:"_full", section2:"fine",section3:"throw",sound:"throw"),
            Quiz(answer:"walk",section1:"walk", section2:"write",section3:"jump",sound:"walk"),
            Quiz(answer:"eat",section1:"meat", section2:"eat",section3:"cheap",sound:"eat"),
            Quiz(answer:"write",section1:"cheap", section2:"sad",section3:"write",sound:"write"),
        ]],
//        状態
        [[
        Quiz(answer:"good",section1:"good", section2:"happy",section3:"fine",sound:"good"),
        Quiz(answer:"bad",section1:"big", section2:"bad",section3:"bag",sound:"bad"),
        Quiz(answer:"big",section1:"bag", section2:"bad",section3:"big",sound:"big"),
        Quiz(answer:"small",section1:"small", section2:"sad",section3:"big",sound:"small"),
        Quiz(answer:"strong",section1:"sleepy", section2:"strong",section3:"_hot",sound:"strong"),
        Quiz(answer:" _weak",section1:"good", section2:"angry",section3:"_weak",sound:"weak"),
        Quiz(answer:"heavy",section1:"heavy", section2:"big",section3:"happy",sound:"heavy"),
        Quiz(answer:"little",section1:"write", section2:"little",section3:"busy",sound:"little"),
    ],[
        Quiz(answer:"cheap",section1:"cook", section2:"kick",section3:"cheap",sound:"cheap"),
        Quiz(answer:"expensive",section1:"expensive", section2:"clean",section3:"sad",sound:"expensive"),
        Quiz(answer:"clean",section1:"cook", section2:"clean",section3:"thirsty",sound:"clean"),
        Quiz(answer:"dirty",section1:"draw", section2:"dance",section3:"dirty",sound:"dirty"),
        Quiz(answer:"_dry",section1:"_dry", section2:"dance",section3:"_full",sound:"_dry"),
        Quiz(answer:"wet",section1:"good", section2:"wet",section3:"tired",sound:"wet"),
        Quiz(answer:"_hot",section1:"hotdog", section2:"clean",section3:"_hot",sound:"_hot"),
        Quiz(answer:"_cold",section1:"_cold", section2:"cap",section3:"_cut",sound:"_cold"),
    ],[
        Quiz(answer:"fast",section1:"fine", section2:"fast",section3:"west",sound:"fast"),
        Quiz(answer:"slow",section1:"clean", section2:"light",section3:"slow",sound:"slow"),
        Quiz(answer:"high",section1:"high", section2:"fine",section3:"wet",sound:"high"),
        Quiz(answer:"low",section1:"kind", section2:"low",section3:"slow",sound:"low"),
        Quiz(answer:"new",section1:"wet", section2:"little",section3:"new",sound:"new"),
        Quiz(answer:"old",section1:"old", section2:"_dry",section3:"cook",sound:"old"),
        Quiz(answer:"noisy",section1:"busy", section2:"noisy",section3:"good",sound:"noisy"),
        Quiz(answer:"quiet",section1:"a lot of", section2:"famous",section3:"quiet",sound:"quiet"),
        Quiz(answer:"easy",section1:"easy", section2:"which",section3:"noisy",sound:"easy"),
        Quiz(answer:"difficult",section1:"light", section2:"difficult",section3:"throw",sound:"difficult"),
    ],[
        Quiz(answer:"dark",section1:"short", section2:"sick",section3:"dark",sound:"dark"),
        Quiz(answer:"light",section1:"light", section2:"belt",section3:"get up",sound:"light"),
        Quiz(answer:"long",section1:"light", section2:"long",section3:"short",sound:"long"),
        Quiz(answer:"short",section1:"light", section2:"good",section3:"short",sound:"short"),
        Quiz(answer:"tall",section1:"tall", section2:"_full",section3:"a lot of",sound:"tall"),
        Quiz(answer:"thin",section1:"tall", section2:"thin",section3:"young",sound:"thin"),
        Quiz(answer:"thick",section1:"sick", section2:"kick",section3:"thick",sound:"thick"),
        Quiz(answer:"young",section1:"young", section2:"angry",section3:"strong",sound:"young"),
        Quiz(answer:"pretty",section1:"sometimes", section2:"pretty",section3:"happy",sound:"pretty"),
        Quiz(answer:"wonderful",section1:"_full", section2:"how",section3:"wonderful",sound:"wonderful"),
        Quiz(answer:"kind",section1:"kind", section2:"quiet",section3:"cook",sound:"kind"),
        Quiz(answer:"famous",section1:"forty", section2:"famous",section3:"_full",sound:"famous"),
        Quiz(answer:"popular",section1:"popcorn", section2:"laugh",section3:"popular",sound:"popular"),
    ],[
        Quiz(answer:"sometimes",section1:"sometimes", section2:"often",section3:"who",sound:"sometimes"),
        Quiz(answer:"often",section1:"far", section2:"often",section3:"thick",sound:"often"),
        Quiz(answer:"again",section1:"often", section2:"thick",section3:"again",sound:"again"),
        Quiz(answer:"far",section1:"far", section2:"wonderful",section3:"what",sound:"far"),
        Quiz(answer:"more",section1:"often", section2:"more",section3:"who",sound:"more"),
        Quiz(answer:"many",section1:"more", section2:"what",section3:"many",sound:"many"),
        Quiz(answer:"a lot of",section1:"a lot of", section2:"what",section3:"noisy",sound:"a lot of"),
        Quiz(answer:"how",section1:"far", section2:"how",section3:"a lot of",sound:"how"),
        Quiz(answer:"who",section1:"often", section2:"far",section3:"who",sound:"who"),
        Quiz(answer:"what",section1:"what", section2:"more",section3:"far",sound:"what"),
        Quiz(answer:"which",section1:"whose", section2:"which",section3:"what",sound:"which"),
        Quiz(answer:"whose",section1:"again", section2:"often",section3:"whose",sound:"whose"),
    ]
        ]
    ]
}
